#!/usr/bin/env bash

RED='\033[31m'
GREEN='\033[32m'
YELLOW='\033[33m'
BASE='\033[0m'

fill_makefile()
{
	echo -e 'NAME = \n\n' > Makefile
	echo -e 'CC = GCC' >> Makefile	
	echo -e 'CFLAGS = -Wall -Werror -Wextra' >> Makefile
	echo -e 'INCLUDES = $(addprefix -I, includes)' >> Makefile
	echo -e 'CC = GCC\n' >> Makefile
	echo -e 'LIB = libft/libft.a\n' >> Makefile
	echo -e 'SRC = \n' >> Makefile
	echo -e 'SRCS = $(addprefix srcs/, $(SRC))\n' >> Makefile
	echo -e 'OBJ = $(SRCS:.c=.o)\n\n' >> Makefile
	echo -e 'all:$(NAME)\n\n\n' >> Makefile
	echo -e '$(LIB):\n		make -C libft\n' >> Makefile
	echo -e 'clean:\n		make clean -C libft\n' >> Makefile
	echo -e 'fclean:clean\n		make fclean -C libft\n		rm -rf $(OBJ)\n' >> Makefile
	echo -e 're:fclean\n		make all\n' >> Makefile
}

touch_files_and_folders()
{
	touch Makefile
	fill_makefile
	echo -e "${YELLOW} === Makefile created ===${BASE}"
	touch auteur
	echo $LOGIN > auteur
	echo -e "${YELLOW} === auteur created ===${BASE}"
	mkdir srcs
	mkdir includes
	cd includes
	touch "$1.h"
	cd ..
	echo -e "${YELLOW} === srcs/, includes/ and $NAME.h created ===${BASE}"
}

clone_libft()
{
	git clone https://github.com/VirgileVP/libft libft
	cd libft
	rm -rf .git
	cd ..
	echo -e "${YELLOW} === libft cloned ===${BASE}"
}

commands()
{
	echo " Usage : ./03 [-h -p -l -L -d]"
	echo "    -h : help"
	echo "    -p [Project name] : specify project name"
	echo "    -l [login] : specify your login"
	echo "    -d [directory name] : add additional directory"
	echo "    -L : CLone libft"
	exit 1
}

create_project()
{
	mkdir "$NAME"
	cd "$NAME"
	touch_files_and_folders $NAME $LOGIN

	if [ -e "$LIBFT" ]
		then
			clone_libft

	fi
	if [ -n "$ADD_DIR" ]
		then
			mkdir $ADD_DIR
			echo -e "${YELLOW} === $ADD_DIR created ===${BASE}"
	fi
	
	cd ..
	echo -e "${GREEN} === PROJECT CREATED ===${BASE}"
}

if [ "$#" -eq 0 ]
	then
		commands
	else
		while getopts ":p:l:d:hL" OPTION
		do
			case $OPTION in
				h)
					commands
					exit 1
					;;
				p)
					NAME="$OPTARG"
					;;
				l)
					LOGIN="$OPTARG"
					;;
				L)
					LIBFT=1
					;;
				d)
					ADD_DIR="$OPTARG"
					;;
				:)
					echo -e "${RED} $OPTARG : Missing argument ! Check ./03 -h${BASE}"
					exit 1
					;;
				\?)
					echo -e "${RED} $OPTARG : Invalid option !${BASE}"
					exit 1
					;;
			esac
		done 2>/dev/null
		create_project $NAME $LOGIN $LIBFT $ADDDIR
		exit
fi
